drop sequence "BACKOFFICE"."TRX_EXCHANGE_RATE_SEQ";

CREATE SEQUENCE "BACKOFFICE"."TRX_EXCHANGE_RATE_HEADER_SEQ"
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE "BACKOFFICE"."TRX_EXCHANGE_RATE_DETAIL_SEQ"
    START WITH 1
    INCREMENT BY 1
    NOCACHE;